name: docker build and push
on: 
    push
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3   
            - name: Building the Docker Image
              uses: docker/build-push-action@v6
              with:
                push: false
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:${{ github.sha }}
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
            - name: Installing trivy
              run: |
                wget https://github.com/aquasecurity/trivy/releases/download/v0.20.2/trivy_0.20.2_Linux-64bit.deb
                sudo dpkg -i trivy_0.20.2_Linux-64bit.deb

            - name: Download HTML Template
              run: |
                curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o trivy-html.tpl
            - name: Run Trivy Scan
              run: |
                trivy image --format template --template @trivy-html.tpl --output trivy-report.html ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
                trivy image --format json --output trivy-report.json ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
              
              # Step 8: Upload HTML Report as an Artifact
            - name: Upload Trivy HTML Report
              uses: actions/upload-artifact@v3
              with:
                name: trivy-html-report
                path: trivy-report.html        
            
            #     # Step 6: Upload Trivy scan report as an artifact
            # - name: Upload Trivy scan report
            #   uses: actions/upload-artifact@v3
            #   with:
            #     name: trivy-report
            #     path: trivy-report.json
