name: docker build and push
on: 
    push
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3   
            - name: Building the Docker Image
              uses: docker/build-push-action@v6
              with:
                push: false
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:${{ github.sha }}
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest

            - name: Cache Trivy Database
              uses: actions/cache@v4
              with:
                path: ~/.cache/trivy
                key: trivy-db-${{ runner.os }}-${{ hashFiles('/Dockerfile') }}
                restore-keys: |
                  trivy-db-${{ runner.os }}-
        

            - name: Scan Docker image with Trivy
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
                format: 'json'  # You can also use 'table' or 'sarif'
                output: 'trivy-report.json'
            
                # Step 6: Upload Trivy scan report as an artifact
            - name: Upload Trivy scan report
              uses: actions/upload-artifact@v3
              with:
                name: trivy-report
                path: trivy-report.json
