name: docker build and push
on: 
    push
jobs:
    docker_build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3   
            - name: Building the Docker Image
              uses: docker/build-push-action@v6
              with:
                push: false
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:${{ github.sha }}
                  ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/spc:latest
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'
