---
name: ci-worflow
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: build java code using maven
    runs-on: ubuntu-24.04
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - run: tree
      - name: setup java 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: temurin
      - name: execute clean package
        run: ./mvnw package
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spc-artifact
          path: "**/.jar"
        
