name: spc build
on: push
env:
  owner: Production
  environment: Quality Analysis
  Version: v1.0
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '17'
           cache: maven
       - name: maven build
         run: ./mvnw -B verify
       - name: adding environmental variables
         run: |
           echo "The owner of the build is $owner"
           echo "The Environment is $environment"
           echo "The version of the product is $Version"
           echo "Information regarding project $DATE"
